language: go

go:
  - 1.10.x

install:
  - go get -v -t .
  - go get -v github.com/mattn/goveralls
  - go install -v github.com/mattn/goveralls

script:
  - go test . -covermode count -coverprofile cover.out
  - go test ./internal/...
  - goveralls -service travis-ci -repotoken $COVERALLS_TOKEN -coverprofile cover.out

notifications:
  email: false