version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/maxence-charriere/go-app
    steps:
      - checkout
      - run: go get github.com/stretchr/testify/require
      - run: go vet ./...
      - run: go test -v -race ./...
