name: Testing

on: [push]

jobs:
  code:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check Go Code
        run: go vet ./...
  server:
    name: Server Side Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Unit Tests
        run: go test -v -race ./...
