name: Testing

on: [push]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Check Go Code
        uses: go vet ./...
